### ISSUE TITLE
HidDevice is null after opening

### ISSUE THREAD

**Issue by omegablitz** [nyholku/purejavahidapi#1]
My device variable is null after doing the following:

pastebin: http://pastebin.com/N6i74J3U

List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
for (HidDeviceInfo info : devList) {
    if(info.getVendorId() == (short)0x54C) {
        try {
            System.out.println(info.getPath().toString());
            HidDevice dev = (HidDevice) PureJavaHidApi.openDevice(info.getPath());
            //dev is null?
        } catch (IOException e) {
            e.printStackTrace();
            break;
        }
    }
}

It manages to find the device with the right ID and will get the device's info, but the device is null when opened. Any idea as to why? I am a beginner at this sort of stuff so bear with me...
Thanks!

**Comment by xiaoyinliuyun** [comment]
windows OS  ,HIDDeviceInfo .open is null.   Mac OS isn't null.  why???
