### ISSUE TITLE
Sending data works, but receiving data does not

### ISSUE THREAD

**Issue by pk72** [nyholku/purejavahidapi#10]
Hello,
I am not sure if this is a bug at all, but as this seems to be the only way to get in touch with you I am trying this way.
I tried to test purejavahidapi with a HID device that I built myself that loops back received data for testing.
The java code follows your examples (see below. I am also a Java novice).
Sending with setOutputReport works fine, as can be seen from the console output and the HID device indicates propper reception of the data.
Receiving the data back does not work (no console output from the inputReportListener) although the HID device indicates that data was successfully sent back. Also the HID device does work (send and receive) in conjunction with an android host.

Can you give me a hint how to debug this further, I mean to look if the windows driver does not receive the report or if the report is received but the inputReportListener is not called.

Thank you
Philipp

OS: windows 7
Java JDK 1.8

My code to test HID loopback:

package usb_mit_purejavahidapi;
import java.util.List;
import purejavahidapi.*;
public class USB_mit_purejavahidapi {
    
    // Atmel HID generic example VID, PID
    private static final short VENDOR_ID = 0x03eb;
    private static final short PRODUCT_ID = 0x2402;
    
    private static final byte[] DATA = new byte[] { 0x01, 0x02, 0x03, 0x04, 
        0x05, 0x06, 0x07, 0x08 };
    private static final int LENGTH = 8;
    
    static boolean receivedFlag = false;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            // search for device with vENDOR_ID and PRODUCT_ID
            List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
            HidDeviceInfo devInfo = null;
            for (HidDeviceInfo info : devList) {
                    if (info.getVendorId() == VENDOR_ID && info.getProductId() == PRODUCT_ID) {
                            devInfo = info;
                            break;
                    }
            }
            if (devInfo == null)
                    System.err.println("device not found");
            else {
                // open device
                HidDevice dev = PureJavaHidApi.openDevice(devInfo.getPath());
                if (dev == null)
                    System.err.println("cannot open device");
                // register input report listener
                dev.setInputReportListener(new InputReportListener() {
                        @Override
                        public void onInputReport(HidDevice source, byte Id, byte[] data, int len) {
                            // change flag in order for waiting loop to finish
                            receivedFlag = true;
                            System.out.printf("onInputReport: id %d len %d data ", Id, len);
                            for (int i = 0; i < len; i++)
                                    System.out.printf("%02X ", data[i]);
                            System.out.println();
                        }
                });
                // send data
                int returnValue = dev.setOutputReport((byte) 0, DATA, LENGTH);
                System.out.printf("setOutputReport return value is %d", returnValue);
                System.out.println();
                // wait until loopback input is received
                while(receivedFlag == false) {
                    java.lang.Thread.sleep((long) 10);
                }
                System.out.print("End of code");
            }
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
}

**Comment by nyholku** [comment]
Hi,

couple of ideas.

1) 'receivedFlag' should maybe be 'volatile' as it is not guaranteed that value you set in input report listener is visible to the the main thread.

2) I'n not sure if the input report listener thread is already ready to receive data by the time you call the setOutputReport so it might miss the first few input reports. You could try by adding a 100 msec (BTW you don't need (long) there) delay before you set the output report. Or you could send several output reports before you start waiting for the input report. In fact I don't know if there is a guaranteed happened-before relationship with input/output reports i.e. if you set an output report you may still receive input reports that happened before you send the output report. There is likely buffering in the OS and it also depends on the device firmware I would think.

br Kusti

**Comment by pk72** [comment]
Hey Kusti,
thank you for taking the time to answer.

>1) 'receivedFlag' should maybe be 'volatile' as it is not guaranteed that value you set in input report listener is visible to the the main thread.

Right, thank you. Still I would see the output from the listener as soon as onInputReport() is called, which is not the case.

>2) I'n not sure if the input report listener thread is already ready to receive data by the time you call the setOutputReport so it might miss the first few input reports.

I tried this to no avail.

In the meantime I checked the HID device with some other windows apps:
-Atmel app to test HID firmware, based on Atmel USB-dll, probably uses HID class generic driver: send and receive is working.
-Microsoft HID example app, send not tested, receive works fine.

I am still looking for a way to debug this. If I am setting breakpoints in runReadOnBackground() I expect to not see a thing because nothing is received. I will try nevertheless.
To do so, I will need to put the purejavahidapi sources in my project instead of the .jar. Is this right?

Thank you
Philipp

**Comment by nyholku** [comment]
Yes, you need the source, depending on your IDE the easiest way is just to download the source from github like a zip file and then just copy the src folder contents into your projects src folder.

**Comment by pk72** [comment]
ok, thank you for your help, it does work now and problems were in my code not yours.
Thank you for this elegant library that does without any additional C library and tons of other wrappers.
I did experience however the same issue as described by Iorenberg in issue #12: putting the sources in my project works fine, when I use your jar, the time between received reports is up to 500-1000ms.

**Comment by nyholku** [comment]
Thanks for the reminder I will try to get around to updating the jars.
