### ISSUE TITLE
How to send data to usb

### ISSUE THREAD

**Issue by mohamnexus** [nyholku/purejavahidapi#13]
Hi
I work on a project and i necessary send and receive data from USB.
i can receive byte from USB hid with your API.
but i dont now how to use method for send data to USB?
please give me a example.
thanks.

**Comment by nyholku** [comment]
Use the setReport() method from HidDevice:

	public int setOutputReport(byte reportID,byte[] data, int length);

If your device does not use numbered reports pass 0 for reportID.

So something like this:


    HidDevice dev = PureJavaHidApi.openDevice(devInfo.getPath());
    byte[] data=new byte[] {1,2,3,4,5,7}; // my data
    dev.setOuputReport(0,data,data.length);

**Comment by mohamnexus** [comment]
thanks for comment but error in setReport() statement :
my code is:

package usb01;

import java.awt.HeadlessException;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

import purejavahidapi.*;
import purejavahidapi.HidDevice;

/**
 *
 * @author Mohammad
 */

public class USB01    {

    public static void main(String[] args) throws InterruptedException  {
        try {
            List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
            HidDeviceInfo devInfo = null;
            for (HidDeviceInfo info : devList) {
              
                if (info.getVendorId() == (short) 0x0810 && info.getProductId() == (short) 0x0001) {
                    devInfo = info;
                    System.out.println(devInfo);
                    JOptionPane.showMessageDialog(null, "ok find device");
                    break;
                }
            }
            if (devInfo == null)
                JOptionPane.showMessageDialog(null, "cant find");		
            else {
                HidDevice dev = PureJavaHidApi.openDevice(devInfo.getPath());
                byte[] data=new byte[] {1,2,3,4,5,7}; // my data
                dev.setOuputReport(0,data,data.length);// error in here??
            }
        }
        catch (HeadlessException | IOException e) {
        }
    }
}
please help me.
thanks.

**Comment by nyholku** [comment]
So what error do you get?

And don't add empty 'catch' statements, you'll regret that later�

**Comment by mohamnexus** [comment]
error in picture:
![image](https://cloud.githubusercontent.com/assets/12671085/8249146/6ba84de8-167c-11e5-988e-9a8f958fdea6.png)

**Comment by nyholku** [comment]
On 19 Jun 2015, at 10:42, mohamnexus <notifications@github.com> wrote:

> error in picture:
> 
> 
> �
> Reply to this email directly or view it on GitHub.
> 


Looks like you are using the .jar files from github which are out of date,
try to compile from the source code, also good for debugging because you 
can then step inside PureJavaHidApi code

br Kusti

**Comment by mohamnexus** [comment]
hi
sorry,i tried but i cannot send data to usb.
can you create project in netbeans (for send data to usb with your library) and give me that project(link for download)?
please help me.
thanks

**Comment by nyholku** [comment]
Hi, no, sorry, I don't do netbeans and besides it you are not 'doing your homework' and I'm not doing it for you. If you tried what I suggested (i.e. used the sources not the jars) then you now have a new error (because your previous error was 'cannot find symbol' which must now be gone) but you have not communicated what that new error is. Or communicated that you now have no error. You need to report what your symptoms are, not just that it does not work and can you please make it work for me,

**Comment by AlexBGar** [comment]
Hi
I have got past the device opening and am now, without sucess, trying to send data to my device. I have added the line

        int len = dev.setOutputReport(reportID, outputBuffer, 2);

after I open the device and I get the stack trace

My Device = 2414 771
device found 2414 771 null null \\?\hid#vid_096e&pid_0303#7&3b2f952&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=1, offset=3
	at com.sun.jna.Memory.boundsCheck(Memory.java:185)
	at com.sun.jna.Memory.write(Memory.java:307)
	at purejavahidapi.windows.HidDevice.setOutputReport(HidDevice.java:146)

The line in question reads
 		m_OutputReportMemory.write(1, data, 0, length);

Alex

**Comment by nyholku** [comment]
Did you change the line 94:

from
		m_OutputReportMemory = new Memory(m_OutputReportLength);

to

		m_OutputReportMemory = new Memory(m_OutputReportLength+1);

also is your 

data.length >= length 

?

**Comment by AlexBGar** [comment]
Yes line 94 was changed as it caused an error

data.length was > lenght.
I have tried it this morning with data..length = length

Neither way seems to work

**Comment by AlexBGar** [comment]
I have determined that I must change  line 94 
m_OutputReportMemory = new Memory(m_OutputReportLength);
so that the length is 1 more than the length of my data buffer.  To send 1 byte I must add +2, and to send 8 bytes, I must add +9

Havivg done that, I still get an error

My call is

        int len = dev.setOutputReport(reportID, outputBuffer, outputBuffer.length  );
        System.out.println("bytes sent = " + len);
This results in the message

bytes sent = -1
ReadFile failed with GetLastError()==0

Any idea to what is going wrong?

Alex

**Comment by gurdian0614** [comment]
Hi there, an observation: missing t in output
dev.setOuputReport(0,data,data.length); is
dev.setOutputReport(0,data,data.length);
Regards

**Comment by gurdian0614** [comment]
Hi There, I found the solution:
````
try {
            List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
            HidDeviceInfo devInfo = null;
            for (HidDeviceInfo info : devList) {
                if (info.getVendorId() == (short) 0x1234 && info.getProductId() == (short) 0x0001) {
                    devInfo = info;
                    break;
		}
            }
            if (devInfo == null)
                System.err.println("device not found");
            else {
                HidDevice dev = PureJavaHidApi.openDevice(devInfo.getPath());
                byte[] data=new byte[] {'O','U','T','1','_','0'}; // my data
                dev.setOutputReport((byte)0,data,data.length);
                dev.close();
            }
	} catch (Exception e) {
            e.printStackTrace();
	}
````
Put (byte) in 0 else show the error message: Incompatible types. Possibly lossy conversion from int to byte. I use Netbeans 8.0.2

````
dev.setOutputReport((byte)0,data,data.length);
````

Regards.
Gurdian

**Comment by nyholku** [comment]
Hi, thanks for suggestion. However I think Netbeans is being over zealous here. Eclipse (with default error reporting) is not complaining and nor is javac. In fact I would say this is a bug in Netbeans as there can not be any loss of precision here and Netbeans has to know it because this is a literal here.

**Comment by nyholku** [comment]
Not heard from this since, so I'm closing this, please feel free to re-open if necessary.

**Comment by MrHazee** [comment]
Hi there Nyholku!
First, thanks a bunch for this library!! 
It works perfect except for one little thing. 
It seems that setOutputReport(data[], len) doesnt reset after a transmission. If I send, say 10 bytes, Seven times with setOutputReport() I get an error something like: ”out of memory bounds. Memory limit is 64”.
Do you know why I get this error? I should add that im using the jars from github.
Would really appreciate if you could plint me in the right direction.
Best regards from Sweden
/Rasmus

**Comment by nyholku** [comment]
You should compile from the source, the jars are not up to date. And please report success/failure here.

**Comment by MrHazee** [comment]
Ok, thanks for answer. So, is it hard to compile the lib from source code? havnet done that yet. Is this the right way to go: https://guides.gradle.org/building-java-libraries/
Or is there evan a more simple way?
thanks /R

**Comment by MrHazee** [comment]
..or maybe I just import the source files to my prject and import that package to my code?! Sorry for this newbie question...

**Comment by nyholku** [comment]
> On 22 Mar 2018, at 13:08, MrHazee <notifications@github.com> wrote:
> 
> ..or maybe I just import the source files to my prject and import that package to my code?! Sorry for this newbie question...
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


That is the easiest way and which I often prefer because then it is easy to debug the library...

**Comment by MrHazee** [comment]
Thanks a lot for the fast answers! Will report success/failure. Thanks /R

**Comment by MrHazee** [comment]
Ok, so I now run source code. Still getting unwanted onInputReports().
I have a usb-device that Im communicating with and I already have a working application that is windows only, and now im building an application in Java, cross-platform. If I connect both applications to the usb-device and send a message from the already working application, I only get ONE (wanted) onInputReport() to the new Java-app. This narrows it down to that the problem probably lays in either setOutputReport() itself, or in my code..? Not in the onInputReport().
So, maybe it is because I call setOutputReport from another thread than my PureJavaHidDevice is using?
Maybe that will mess up the timing or something?
Any ideas?
Thanks

**Comment by nyholku** [comment]
Can elaborate what happens in more detail and in sequence. You have one application that does setOutputReport() , the device responds with input report which you catch in an other application with onInputReport()... be specific.

**Comment by MrHazee** [comment]
Thats is correct.
I have two application. One that im developing and one fully functional (windows only c++) from Microship.
If I do setOutputReport in the Java app, I get one responsetwo the win-app but TWO back to the JAVA app.
If I do the corresponding function call (setOutputReport) on the win-app, I get one resnonse to win-app, and only one to the Java-app. So when I send commands from win-app, everything seems to work perfect. 
Its almoast like its an internal loop in the java app..
best regards /Rasmus

**Comment by nyholku** [comment]
Functionally / struturally / logic wise PureJavaHidApi is very close to signal11/HIDAPI. It might provide more clues to the problem if you tried this with HIDAPI, it is rather trivial to write simple C test code with HIDAPI to see if it behaves differently. 

https://github.com/signal11/hidapi

**Comment by MrHazee** [comment]
Tried hid4java and got it to work. Still not sure what caused the issue, but thanks a lot for your replies!!
