### ISSUE TITLE
How to use DeviceRemovalListener

### ISSUE THREAD

**Issue by AlexBGar** [nyholku/purejavahidapi#16]
Hi

Extending your example2 as a JavaFX program, I can receive data from my device using the setInputReport Listener and also close the device but I cannot see how to implement the DeviceRemovalListener. When I remove my device I get the message

GetOverlappedResult failed with GetLastError()==1167
ReadFile failed with GetLastError()==0

Your help would be appreciated

Alex

**Comment by androb4** [comment]
You implement DeviceRemovalListener the same way you create the InputListenerReport.

So for Example 2 it would be like this:
dev.setDeviceRemovalListener(new DeviceRemovalListener() {
					@Override
					public void onDeviceRemoval(HidDevice source) {
						// Do stuff
					}
				});

**Comment by AlexBGar** [comment]
Hi

Did that but it did not work. I am using pureJavaHIDApi as part of a JavaFX program. If, as you say, the RemovalListener does work, then I suspect that my problem is with the threads. I will attempt to put my version of example2 onto a seperate thread.

I am using Netbeans as my development system and I cannot get example2 to work with it as a straight Java program. I have copied example2 and put the 3 jars into the library but I get the error

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/Platform
	at purejavahidapi.PureJavaHidApi.<clinit>(PureJavaHidApi.java:110)
	at example2.Example2.main(Example2.java:22)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Platform .. etc

line 22 is:
            List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();

I don't know what is happening here. This routine works with my JavaFX version

If you want a copy of my FX program, send me an email to abg@eco-wand.com and I will send you it.

**Comment by AlexBGar** [comment]
I have tried putting the USB system onto a seperate thread on my FX program. It didn't make any difference.  My full test programs can be downloadded from Dropbox at

https://www.dropbox.com/sh/oy5aa4y9a851le8/AAByS8yHZ0LYfn2CM2F-Owtea?dl=0

Hope this helps to identify my problems

Alex

**Comment by androb4** [comment]
I copied your example 2 class into my project and it ran fine. You say "3" JARs?

Also, for your project are you using the compiled JAR that used to be in this repo, or did you compile your own from the source? The one that used to being this repo was outdated and you must compile your own.

**Comment by AlexBGar** [comment]
Hi
I compiled my own - I had to change it as my device has 0 length. I am running on Window (just upgraded to Win10 but haven't tested my program yet - it was tested with Win8.1 and Java8.40).

Have you tried to run my JavaFX example?  My device sends 8 bytes every 100mSec or so but, as I said, the RemovalListener doesn't respond.

**Comment by AlexBGar** [comment]
I now have Example2 as supplied working (the jna.jar file had not copied properly). Adding the device removal listener makes no difference, I still get the error message

    GetOverlappedResult failed with GetLastError()==1167
    ReadFile failed with GetLastError()==0

I tried reducing the frequency of sending data but that didn't cure the problem.

I am working on a PC with Win10 (I was using Win8.1 last week so that is not the problem) With Java8_40 and using Netbeans as my development system. I have recompiled the pureJavaHidApi so as to incorporate the device length 0 modifications.

Any ideas on what is going wrong?

**Comment by nyholku** [comment]
From Windows documentation:

ERROR_DEVICE_NOT_CONNECTED
1167 (0x48F)
The device is not connected.

So it appears that Windows things the device is no longer there (connected) ...?

**Comment by AlexBGar** [comment]
That's right, the device isn't there because I removed it. Surely that is what the removal listener is there for - so that I can do something to tell my user that the device isn't there. At present the program just crashes.

**Comment by nyholku** [comment]
Sorry, I thought I was responding to an other thread.

**Comment by AlexBGar** [comment]
Any idea when you will get the Windows DeviceRemovalistener to work?

**Comment by nyholku** [comment]
No idea, I've had a look at it and it appears non-trivial to implement so atm I have no time for this.

**Comment by AlexBGar** [comment]
Hi, Any idea yet when you will get round to fixing the DeviceRemovalListener for Windows?

**Comment by nyholku** [comment]
No, like I said, it is not trivial and I cannot afford the time to investigate it at the moment.

**Comment by AlexBGar** [comment]
Any progress to report on the DeviceRemovalListener for Windows?

**Comment by AlexBGar** [comment]
There does not seem to be much happening with this program. Are you still working on it and my difficulties with the DeviceRemovalListener for Windows?

**Comment by nyholku** [comment]
Hi,

no, like I said, I'm not actively working on this issue. 

All the other functionality seems to work fine and this particular 
feature is not trivial to implement so it will have to wait until 
other projects or my own needs give is more priority.

How about having a go at it yourself, this is after all open source...
or if you can find some other open source project that implements
this then I might have a look at that and see if the implementation
could be 'lifted' from there.

br Kusti

**Comment by nyholku** [comment]
The latest release 0.0.2 contains my first attempt at implementing the device removal listener functionality for Windows.
