### ISSUE TITLE
Running the system on Linux and Mac

### ISSUE THREAD

**Issue by AlexBGar** [nyholku/purejavahidapi#17]
I have developed my program on a Windows computer. Will the resultand jar file run on Linux and Mac computers without any further work or will I have to compile them on the target operation system?

Alex

**Comment by androb4** [comment]
> I have developed my program on a Windows computer. Will the resultand jar file run on Linux and Mac computers without any further work or will I have to compile them on the target operation system?
> 
> Alex

So far my project has been working on both Windows and OS X. I developed it on OS X.

**Comment by nyholku** [comment]
Yes, it should work on all supported platforms, however testing is mandatory on all platforms!
