### ISSUE TITLE
Multiple DeviceRemovalListener

### ISSUE THREAD

**Issue by androb4** [nyholku/purejavahidapi#18]
>The DeviceRemovalListener.onDeviceRemoval(purejavahidapi.HidDevice) method of the device listener object will be called if and when the device is unexpectedly un-plugged. There can be only one device removal listener at a time but it is possible to re-set the listener.

In the JavaDoc it says that there can only be one listener at a time. Does this mean only one listener per device or is it only one listener globally?

I tried setting listeners for two devices but only the most recent listener gets called. It also seems that when I open a device and set the listener, then just open another device, the listener for the first doesn't get called. On another test, I did the same but only setting the listener to the second device, and it seems to be getting called correctly.

How is it possible that there can only one removal listener?
Is this something for future releases?
Or is there a suggested method to achieve something similar?

-Andres

**Comment by nyholku** [comment]
Why would you need multiple DeviceRemovalListeners?

A single device cannot be shared between applications so it seems pointless to support multiple listeners.

A trivial workaround is to set a listener that maintains its own set of listeners to which it broadcasts the event.

As the set device listener is a method of the device this implies that the listener is per device, not global.

wbr Kusti

**Comment by androb4** [comment]
I need multiple listeners because I can have up to 2 his gamepad opened in a single application.

I need the input data to be reset on disconnect for safety purposes. I cannot keep the last read value as the application will think that value is still valid.

**Comment by nyholku** [comment]
But each gamepad will have it's own HidDevice object and both will have their own listeners, one/per device.

**Comment by androb4** [comment]
Exactly. But it still doesn't seem to work..

**Comment by nyholku** [comment]
So one handler per device is fine with you but you think there is a bug? 

Possible, can you share your code or create a demo case?

How do you test this, on what platform/OS, which device?

**Comment by androb4** [comment]
> So one handler per device is fine with you but you think there is a bug?

Correct, that is what I need.

>Possible, can you share your code or create a demo case?

Sure I can do this in about an hour.

I tested it on OS X.

**Comment by androb4** [comment]
Here's a demo of the problem:

https://gist.github.com/androb4/405a99f553c9cc0ffb90

**Comment by androb4** [comment]
Any update on the issue?

**Comment by nyholku** [comment]
Sorry, don't have time for this right now, it looks like this requires the window/service handle to be passed to the windows backend and other complications so I expect this will take a few full days to get to work and I haven't got the time right now.

**Comment by nyholku** [comment]
First attempt at the device removal listener is now available from github. Please open a new issue for any bugs/problems found.
