### ISSUE TITLE
What version of Java does purejavahidapi require?

### ISSUE THREAD

**Issue by AlexBGar** [nyholku/purejavahidapi#19]
I have my system running with Java8_40 on Windows (except for the Removal Listener which is the subject of another posting). My customer has a Linux computer running Java 7 so I have tried converting my system back to Java 7. 

Now I am getting a ClassNotFound error on compilation. I previously had my system working on J7_79 before convertingg it to HID.

Does your system require Java8?

**Comment by nyholku** [comment]
I don't think so, for which class did you get the ClassNotFound ... even if there is some dependency on Java 8 that is purely accidental and should be easy to remove.

**Comment by AlexBGar** [comment]
It works on J8 but not J7.  The error message doesn't tell me which class it hasn't found. Now that I know that it has been tested with J7, I'll investigate further.

**Comment by AlexBGar** [comment]
Got Example2 to work with Java7. I had to re-compile the purejavahidapi.jar file with J7. Using the J8 compiled version gave errors. Going to J7 didn't make the removalListener work.

I will try rebuilding my project in a different way for Java 7 and see if that works

**Comment by nyholku** [comment]
Ok, thanks, I will change the compile to use Java 7 settings.

As to the removalListener, it seems that for Windows this as of today unimplemented. I will put it on my to do list. Sorry I did not spot this earlier, like I said I somehow mixed this with a different issues that plagues the Mac OS X device removal.

**Comment by AlexBGar** [comment]
Hi. Thanks for that information. Do you have a timescale for implementing the device removal listener?

**Comment by nyholku** [comment]
First attempt at the device removal listener is now available from github (darn, not sure if the jars are compiled for Java 7 or 8, will need to check that later).
