### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by omegablitz** [nyholku/purejavahidapi#2]
I know I just had an issue, but I am having another one. Here is the code that is giving the problem:

http://pastebin.com/Ny48wFtV

After saving the device as an instance variable, my program has high cpu usage (~50%). I managed to isolate the problem to this section of the code, because when commented out, the cpu usage drops down to normal levels.

Any idea as to why?

Thanks, and sorry again for asking another question so soon...

**Comment by nyholku** [comment]
I just pushed some changes to the Windows backend you might want try if those help with the high CPU usage (did not have the hardware to test them though so).

**Comment by nyholku** [comment]
Not heard from this since, so I'm closing this, please feel free to re-open if necessary.
