### ISSUE TITLE
OnDeviceConnectedListner

### ISSUE THREAD

**Issue by karunadheera** [nyholku/purejavahidapi#21]
There is no way to receive an event when a device is connected. hid4java library supports this! However I can't use that library since they do not support HidDevice.onInputReport() which is quite nice to have (to capture keypress() etc).

Please implement functionality to receive device connection events.

**Comment by AlexBGar** [comment]
Hi, I get round this by polling the device. If it is not found, I wait 1 second then try again. The DeviceRemovalListener not working in Windows is much more of a problem for me.

abg

**Comment by nyholku** [comment]
Will not be implementing this in near future.
