### ISSUE TITLE
How to receive data from usb

### ISSUE THREAD

**Issue by gurdian0614** [nyholku/purejavahidapi#23]
Hi
I work in a project , I can send data to USB but I can`t receive data from USB.
Please give me an example.
Thanks.

**Comment by nyholku** [comment]
This example receives data from a USB device:

https://github.com/nyholku/purejavahidapi/blob/master/example/Example2.java

**Comment by gurdian0614** [comment]
Great, Thanks
A question: how do you send a command to USB and after receive a data with this command?
e.g: I send the command "IN" to USB and receive data from USB "data=1234."

**Comment by nyholku** [comment]
Hmmm .... how familiar you are with USB basic concepts and especially HID concepts?

I hope I'm no misjudging you but it seems you need do some reading about those.

For HID devices you can't send commands, you send 'reports' if the device accepts them. 

You can also receive 'reports' if the device sends them.

But the input reports are NOT a response to the output reports, those are totally independent conceptually.

It all depends on the device and its firmware.

So you need to know what the device accepts and sends and in which format.

In theory you can parse some of this information from the report descriptor but PureJavaHidApi does not support reading the report descriptors, besides for many devices the descriptor is inadequate.

**Comment by gurdian0614** [comment]
Great, Thanks
