### ISSUE TITLE
ReadFile failed with GetLastError()==0

### ISSUE THREAD

**Issue by zbrowning** [nyholku/purejavahidapi#26]
from windows.HidDevice.java, line 230

I working with a [BlinkStick](https://www.blinkstick.com/). I repeatedly write feature reports to provide the color information.

While that is happening, I get a constant output of the error message. It even happens from a single call to HidDeviceInfo.getSerialNumberString().

Any idea what's happening?

Thanks!

**Comment by nyholku** [comment]
I suggest this might be the kind error I/we had in PureJavaComm project with the GetLastError. My first reaction would be to try to ignore the error (just modify the preceding 'if' statement to check for GetLastError()==0.  Let me know if it works for you with this and I will incorporate the fix. But the actual problem maybe with way JNA is handling GetLastError(). Or it might not be. I will try to find the time to investigate. Which JNA version you are using? If not the latest I suggest trying the latest version.

**Comment by nyholku** [comment]
Hi, it was just pointed out to me that the reporting of  GetLastError() in line 230 here:

https://github.com/nyholku/purejavahidapi/blob/master/src/main/java/purejavahidapi/windows/HidDevice.java

happens after a CancelO call which can overwrite the last error and thus the 'GetLastError()==0' report maybe a wrong. 

To test this hypothesis, please move the println() above the CancelIO.

**Comment by zbrowning** [comment]
I was using JNA 4.0.0 from /lib, but  moved to the latest 4.2.1. After moving the print statement, I'm getting error 1784.

**Comment by nyholku** [comment]
ERROR_INVALID_USER_BUFFER
1784 (0x6F8)
The supplied user buffer is not valid for the requested operation.


On line 106 of purejavahidapi.windows.HidDevice try adding one 1


		m_InputReportLength = caps.InputReportByteLength + 1;

**Comment by zbrowning** [comment]
That solves the issue. Thanks!
