### ISSUE TITLE
HidDevice is null

### ISSUE THREAD

**Issue by tahoser** [nyholku/purejavahidapi#27]
Hi,

In first step I put my hand scaner (LS2208) in USB port ad run code:

		try {
			List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
			HidDeviceInfo devInfo = null;
			for (HidDeviceInfo info : devList) {
				if (info.getVendorId() == (short) 0x05E0 && info.getProductId() == (short) 0x1200) {
					devInfo = info;
					break;
				}
			}
			if (devInfo == null)
				System.err.println("device not found");
			else {
				HidDevice dev = PureJavaHidApi.openDevice(devInfo.getPath());
				dev.setInputReportListener(new InputReportListener() {
                   ......

and was it ok

But next I reset hand scaner (see: page 5 on http://www.hant.pl/instrukcje/czytniki-kodow/motorola/instrukcja-obslugi-motorola-ls2208.pdf)

And now :

PureJavaHidApi.enumerateDevices() return correct list devices with one element (HidDeviceInfo):

VID = 0x05E0 PID = 0x1200 Manufacturer = ﾩSymbol Technologies, Inc, 2002 Product = Symbol Bar Code Scanner Path = \\?\hid#vid_05e0&pid_1200#6&312ca51&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

BUT PureJavaHidApi.openDevice(devInfo.getPath()) return null

(method open_device(path, false) in purejavahidapi.windows.WindowsBackend.openDevice(String, Frontend)) return INVALID_HANDLE_VALUE )

I also restart my computer and have the same effect.

Where is error?

Please help me.

regards,
taho

**Comment by AlexBGar** [comment]
Hi taho
This is part of the method I use. fter this part, I add a Listener and it works fine.

    public static boolean openMyDevice() {
        try {
            List<HidDeviceInfo> devList = PureJavaHidApi.enumerateDevices();
            HidDeviceInfo devInfo = null;
            for (HidDeviceInfo info : devList) {
                if (info.getVendorId() == VID && info.getProductId() == PID) {
                        devInfo = info;
                        break;
                }
            }
            if (devInfo == null){ 
                HIDOpen = false ;
                    return false ;
            }
            else { 
                HIDOpen = true ;
                device = PureJavaHidApi.openDevice(devInfo.getPath());

**Comment by nyholku** [comment]
Not heard from this since, so I'm closing this, please feel free to re-open if necessary.
