### ISSUE TITLE
How to compile project after March 19 merge?

### ISSUE THREAD

**Issue by ivarru** [nyholku/purejavahidapi#29]
The March 19 merge changed the directory structure and introduced pre-built jars.
Was this intentional? I am not a Maven expert. Previously I used:

> mvn clean install

But this no longer works. What is the recommended way to build the project from source now?

**Comment by nyholku** [comment]
No, that was intentinal, which directory structure has changed ... to me it looks identical.

As to maven, I don't know much anything about it. I plan to make the jars available from my server so you can refer to them in a Maven project easily (done this for my PureJavaComm project already) but as to how to compile with maven, I do not know (yet).

I let Eclipse compile the class files and use the provided build-jars.xml ant script to package the jars.

If you want to use javac to compile the classes from command line something like this should do it:

javac -d classes -sourcepath ./src -cp lib/jna.jar src/PureJavaHidApi.java

**Comment by ivarru** [comment]
I see. The file pom.xml seemed to indicate that you use Maven, which expects to find the source files in /src/main/java/... where they used to be located.

Do you plan to publish purejavahidapi to the (Maven) Central Repository?

**Comment by nyholku** [comment]
I don't recall the files ever been in src/main/java 

If the pom file say that, then it is the pom that is wrong, I will need to check that.

I'm not actively trying to publish it to MCR but if it requires little effort (from my part,
contributions welcome) and does not require changes to the project structure them
I'm ok with that.

**Comment by ivarru** [comment]
If you don't remember what the project looked like a couple of weeks ago, you can look at https://github.com/ivarru/purejavahidapi . :smile:

I have never uploaded anything to the Central Repository myself, but it appears to be straightforward (cf. https://maven.apache.org/guides/mini/guide-central-repository-upload.html).

**Comment by nyholku** [comment]
:) yeah I know my history.

Had a look at the maven central thing and looks to me it will take a good afternoon to get all the ducks in pretty row to make that work and I haven't got that afternoon right now i.e. low on my priority list atm. I will try to come back to this at some later date.

**Comment by nyholku** [comment]
AFAIU this is now moot, feel free to re-open if this is still a problem.
