### ISSUE TITLE
Can't use getFeatureReport

### ISSUE THREAD

**Issue by retronicdesign** [nyholku/purejavahidapi#31]
Hello,

I tried to read a getFeatureReport out of my opened HidDevice but I always get -1 (error communicating with device).

I tried with two different devices that have a 5 byte feature report and a 132 bytes feature report.

Do you have a working example of getFeatureReport?

Thank you!

**Comment by nyholku** [comment]
Sorry, I don't have a device that has feature reports, so this in pretty much untested code. I've blindly followed the signal11 HIDAPI code, maybe you can test your device with that:

https://github.com/signal11/hidapi

if that works then we can try to see what is the difference between PureJavaHidApi and HIDAPI code.

**Comment by retronicdesign** [comment]
I'll try this.
I can send you a module that has all its reports as feature.
Works with a commandline in c++ but can't with purejavahidgui.
You can communicate with me at info@retronicdesign.com
Thanks!

**Comment by nyholku** [comment]
Contact me in two week, I'm traveling and will not remember this
when I get home.

br Kusti

**Comment by nyholku** [comment]
This now works for me on MacOS and Linux so I'm closing this until some reports problems
