### ISSUE TITLE
Ubuntu 14.04 - errno 13 opening device

### ISSUE THREAD

**Issue by tresf** [nyholku/purejavahidapi#36]
Steps to reproduce:

1. Fire up Ubuntu 14.04
2. Attach Mettler Toledo PS60 Scale -- Note, any HID device should do (if using a VM, attach through VM)
3. Attempt to open using `PureJavaHidApi.openDevice(devInfo);`

The test passes on Windows and Mac but fails on Ubuntu 14.04.
The test passes using [`hid4java`](https://github.com/gary-rowe/hid4java) -- using equivalent code -- on Ubuntu 14.04 as well.

```
Caused by: java.io.IOException: open() failed, errno 13
	at purejavahidapi.linux.HidDevice.<init>(Unknown Source)
	at purejavahidapi.linux.LinuxBackend.openDevice(Unknown Source)
	at purejavahidapi.PureJavaHidApi.openDevice(Unknown Source)
	... 14 more
```

**Comment by kbaik** [comment]
I have the same problem running on the raspberry pi Linux 4.4.34-v7+

**Comment by nyholku** [comment]
Error 13 is, "access denied" and this means that the operating system has denied access for your so nothing to do with PureJavaHidApi. Either the system has the device in use or you need to set up some udev rules to grant yourself an access. Plenty of examples if you google for it. As a test you can run your code as root, if you can then access the device then you need some access (udev) rules to make it work for you. Linux has some weird default rules that does not allow people to use their own devices, very user un-friendly.

**Comment by tresf** [comment]
@nyholku did you miss the part:

> The test passes using hid4java -- using equivalent code -- on Ubuntu 14.04 as well.

Please reopen.

**Comment by nyholku** [comment]
Well, it is still system error 13 ie access denied and because this does not happen in my system I can't investigate this. If you look at the code it is simple 'open' which either fails or not. To investigate this you need test first as root and the see what extra operations hid4java does to be able to access the device, perhaps is uses some different API to access the device, which I'm not going to do. What device this is? If this is some 'standard' device like mouse, keyboard etc then PureJavaHidApi is the wrong tool for your job, PureJavaHidApi is to access devices that pretend to be HID devices but are actually something else. Like a Oregon Scientific Weather station.

**Comment by tresf** [comment]
>  What device this is?

It's in the original bug report.

We're aware of the [udev rules](https://github.com/qzind/tray/blob/2.0/ant/linux/linux-udev.rules.in) and the device is not a keyboard or mouse, it's a USB attached HID scale made by Mettler Toledo.

The environment I test with is having some trouble today.  Once fixed, I'll be sure to post the output when run as root.

> this does not happen in my system I can't investigate this

Can you please offer information about your environment so that we too have a baseline?

**Comment by nyholku** [comment]
I'm running this in Mint Linux under Parallels Desktop on Mac OS 10.10.5

To access one device I had to add:

    SUBSYSTEMS=="usb", ATTRS{idProduct}=="0a99", ATTRS{idVendor}=="16c0", MODE="0660", SYMLINK+="atarijoystick", GROUP="plugdev"

**Comment by kbaik** [comment]
Thank you so much. Running as Root, I no longer have the problem!! As a side note, I had to update the JNA from the included 4.0.0 to 4.3.0 to avoid some udev related native library loading issue on the Raspberry Pi.

Thank you for the great project. I tried JxInput, HID4JAVA, and USB4JAVA before landing onto your project, and your project is the best that suits my purpose of interfacing with a generic joystick. I see you also have a COM project going on. Keep up the good work.

**Comment by nyholku** [comment]
@tresf glad you made some progress. You probably should not run as root except for testing so you still need to figure out the correct UDEV rules, they can be a pain to debug as there is very little diagnostic support.

And thanks for the kind words.

**Comment by tresf** [comment]
FYI, that was @kbaik's reply, not mine.  I will provide test results as soon as possible.

**Comment by tresf** [comment]
> first as root

Test results:
 * `hid4java` works as standard user
 * `purejavahidapi` requires root

> see what extra operations hid4java does to be able to access the device, perhaps is uses some different API to access the device, which I'm not going to do.

It seems to use the same [`open(path, O_RDWR)`](https://github.com/signal11/hidapi/blob/master/linux/hid.c#L629) technique.  Why would the results be different?  I tried changing `O_RDWR` to `O_RDONLY` to no avail. 😕

**Comment by nyholku** [comment]
Thanks for the report. I have no idea why that is. As it seems you can reproduce the issues I would suggest single stepping into both codes to see what is different.

libusb has a call 'detach_kernel_driver' which can/needs to be used with some some devices because otherwise the OS grabs the device. So maybe hid4java does something similar behind the scenes -- OTH why would the device then work as root but not as std user...

**Comment by nyholku** [comment]
Closing this for now as I cannot reproduce this and the OP has not reported back for three weeks. Feel free to reopen if you think there is something I can work on.

**Comment by tresf** [comment]
>  I cannot reproduce this

I don't see evidence you've tried.  This bug occurs on vanilla Ubuntu 14.04 which is a very common OS in the industry.

> Feel free to reopen if you think there is something I can work on.

When admins close, user's can't reopen.  If it works with hid4java then this bug is a code defect and the bug should be left open until exhausted.  3 weeks is not unreasonable when a PR takes 4 to become merged.  If you want your tracker clean, keep it closed however if you want this library to work on Linux without unnecessary workarounds, I recommend you leave it open.

**Comment by nyholku** [comment]
Sorry if you felt bad about me closing this issue. But I've now re-openened it. And you and everyone else is always free to open an other issue even for the same problem if you so feel.

Now this is open so it reminds us of the problem.

**Comment by tresf** [comment]
@nyholku thanks.  And on an unrelated note, `purejavahidapi` is now our preferred solution for reading HID devices in production environments on Windows.  It has proven much more stable over the alternate HID libraries (`signal11`) in our testing per https://github.com/qzind/tray/issues/119, https://github.com/qzind/tray/issues/152.  👍

**Comment by nyholku** [comment]
Ok. 

Just FYI I'm not actively working on this.

All my testing and experience points to PureJavaHidApi working as planned when the udev rules are correct. It is a mystery why hid4java works if access is denied for PureJavaHidApi. 

 I don't want to go and find out why hid4java works without proper udev rules. I'm no Linux expert but from everything I read I get the impression that proper udev rules are a must if the code is to be able to access a device without being run as root.

Especially as hid4java is based on signal11/HIDAPI and most of the code logic in PureJavaHidApi is identical to HIDAPI.

**Comment by tresf** [comment]
I'm not sure if it's relevant, but this seems like it could be related:

https://github.com/mrpippy/hidapi/commit/d54b4300d674db29513e9665f400af95f65075e9

**Comment by tresf** [comment]
> I don't want to go and find out why hid4java works without proper udev rules.

Me neither.  I'll close this out as there's no interest to fix at the time being.  If that changes, I'll come back and reopen.
