### ISSUE TITLE
GetFeature() on Windows seems to forget last byte of result

### ISSUE THREAD

**Issue by nietamten** [nyholku/purejavahidapi#39]
My fast hack:
in HidDevice.java change line 218 from:
			int n = bytes[0];
to:
			int n = bytes[0]+1;
I guess mistake is about report numer that maybe can not be counted.

**Comment by nyholku** [comment]
Hi, thanks for reporting, this fix should be in the next release. Please re-test when the release happens and report back if the problem persists. I will close this for now.
