### ISSUE TITLE
GetFeature() on windows seems to work wrong when used while receiving input report

### ISSUE THREAD

**Issue by nietamten** [nyholku/purejavahidapi#40]
I'm not sure it is true.
I had problems with device continuously (every 2s) sending input reports and to calling GetFeature().
There is disabled code calling HidD_GetFeature() and i enabled it with 'return lenght' then problem disappeared.
I guess data for input report was mistaken with that for feature report (but i'm not sure it is even possible).

**Comment by nietamten** [comment]
Problem still exists but maybe is harder to achieve. I'm still searching and I'm not sure that problem is in library or in my app.

**Comment by nietamten** [comment]
Update:
When I call GetFeature() I get extra onInputReport() call with last data.
My usb device SHOULD blink when sending input report so its unlikely to be reason.
I'm still not sure it is not my mistake somewhere else.

**Comment by nietamten** [comment]
I think that Windows work like that and... and I'll change my app to work with that extra calls (or leave that exceptions).
On Linux I don't get extra calls. 
For me it's closed... 
If there is some idea what more can I check I can try that.

**Comment by nyholku** [comment]
Ok, thanks for reporting, will close this now.
