### ISSUE TITLE
Mac 10.12 not working

### ISSUE THREAD

**Issue by rwu2359** [nyholku/purejavahidapi#42]
groovy.lang.MissingMethodException: No signature of method: static purejavahidapi.PureJavaHidApi.openDevice() is applicable for argument types: (java.lang.String) values: [USB_0922_8003_0x600000145540]

the API says the open() method needs a string taken from devInfo.getPath() but this just keeps crashing..

**Comment by hanshuebner** [comment]
This was a documentation problem which has since been fixed.  The `openDevice` method requires a `HidInfo` as argument.  This issue can be closed.
