### ISSUE TITLE
Cannot send non-zero report ID in feature reports on MacOS

### ISSUE THREAD

**Issue by hanshuebner** [nyholku/purejavahidapi#46]
If I run `mvn install`, I end up with a basically empty jar in `target/`.  Can you supply instructions for rebuilding the library?

Thanks!
Hans

**Comment by nyholku** [comment]
Sorry, dont't use Maven myself (the .pom was a contributed thing) so can't really help you there, but simple javac should do ti:

mkdir classes
javac -d classes -sourcepath ./src -cp lib/jna.jar src/purejavahidapi/PureJavaHidApi.java

should compile the class files and then 

mkdir bin
jar cf bin/purejavahidapi.jar -C classes .

should create the jar.

Personally I use Eclipse for everything so above maybe have some typos as I did not test them.

If you are modifying the code then the easiest way to do is just dump/include the source code in you IDE.

wbr Kusti

**Comment by hanshuebner** [comment]
Thanks, Kust​i!  Your command line helped me quite a bit.  I need to send a
feature report with a non-zero report ID.  Do you think that an additional
signature setFeatureReport(int reportId, byte[] data, int length) would
make sense in general?  If so, I can add that and open a PR.  If you don't
like it, I can also live with a private version for my experiments.

Cheers,
Hans

**Comment by nyholku** [comment]
"non-zero report ID" well, that depends on if it is in the HID standard or not. If it is I'll implement it, otherwise not.

**Comment by hanshuebner** [comment]
It is part of the HID standard. Some system APIs want the report ID in the
first byte of the data buffer (e.g. Windows), some have it as an extra
argument in the API function (e.g. MacOS).  It would be a great help to me
if I had that feature as I would like to talk to a programmable keyboard
from my Mac which requires the report ID to be 1.

Thanks,
Hans

Am 30.09.2017 11:10 schrieb "nyholku" <notifications@github.com>:

**Comment by nyholku** [comment]
> On 30 Sep 2017, at 12:17, Hans Hübner <notifications@github.com> wrote:
> 
> It is part of the HID standard. Some system APIs want the report ID in the
> first byte of the data buffer (e.g. Windows), some have it as an extra
> argument in the API function (e.g. MacOS). It would be a great help to me
> if I had that feature as I would like to talk to a programmable keyboard
> from my Mac which requires the report ID to be 1.
> 
> Thanks,
> Hans

Ok, I will check the HID standard when I have time and implement this,
or if you feel like you can do it yourself, feel free to fork and
do pull request.

wbr Kusti

**Comment by hanshuebner** [comment]
I digged a little deeper into the code and found that for both Linux and
Window, the report ID for feature reports is assumed to be in the first
byte of the buffer, whereas in MacOS you specify it as constant 0.  I would
think that because it is common to have the report ID in the first byte of
the buffer, it would make sense to follow that convention with MacOS as
well.  That way, no new API method will be needed, but I will just fix the
bug in the MacOS version by taking the report ID from the buffer instead of
passing it as 0.

-Hans

**Comment by nyholku** [comment]
To be consistent I think this needs a new API call:

	abstract public int setFeatureReport(byte reportID, byte[] data, int length);

and the old call deprecated, so this is my plan for the next release.
