### ISSUE TITLE
Parser bug?

### ISSUE THREAD

**Issue by LeviticusMB** [nyholku/purejavahidapi#6]
Trying to parse the following descriptor using the HidParser:

<pre>
058C0902A1010912A1028502150026FF00750895010501093B81029503058C09FB09FC09FD8102953809FE8202020666FF9502090009008102058C25017501950809FF8102C00914A10285041500250175019508095F0960098509869186C006FFFF0901A10285F0150026FF007508953F0902820202953F0903920202C0C0
</pre>

which yields:
<pre>
[  0] = 0x05:  size 1  type GLOBAL    tag USAGE_PAGE            value 0xFFFFFF8C (-116)
[  2] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000002 (2)
[  4] = 0xA1:  size 1  type MAIN      tag COLLECTION            value 0x00000001 (1)
[  6] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000012 (18)
[  8] = 0xA1:  size 1  type MAIN      tag COLLECTION            value 0x00000002 (2)
[ 10] = 0x85:  size 1  type GLOBAL    tag REPORT_ID             value 0x00000002 (2)
[ 12] = 0x15:  size 1  type GLOBAL    tag LOGICAL_MINIMUM       value 0x00000000 (0)
[ 14] = 0x26:  size 2  type GLOBAL    tag LOGICAL_MAXIMUM       value 0x000000FF (255)
[ 17] = 0x75:  size 1  type GLOBAL    tag REPORT_SIZE           value 0x00000008 (8)
[ 19] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000001 (1)
[ 21] = 0x05:  size 1  type GLOBAL    tag USAGE_PAGE            value 0x00000001 (1)
[ 23] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x0000003B (59)
[ 25] = 0x81:  size 1  type MAIN      tag INPUT                 value 0x00000002 (2)
[ 27] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000003 (3)
[ 29] = 0x05:  size 1  type GLOBAL    tag USAGE_PAGE            value 0xFFFFFF8C (-116)
[ 31] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFFFB (-5)
[ 33] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFFFC (-4)
[ 35] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFFFD (-3)
[ 37] = 0x81:  size 1  type MAIN      tag INPUT                 value 0x00000002 (2)
[ 39] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000038 (56)
[ 41] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFFFE (-2)
[ 43] = 0x82:  size 2  type MAIN      tag INPUT                 value 0x00000202 (514)
[ 46] = 0x06:  size 2  type GLOBAL    tag USAGE_PAGE            value 0xFFFFFF66 (-154)
[ 49] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000002 (2)
[ 51] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000000 (0)
[ 53] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000000 (0)
[ 55] = 0x81:  size 1  type MAIN      tag INPUT                 value 0x00000002 (2)
[ 57] = 0x05:  size 1  type GLOBAL    tag USAGE_PAGE            value 0xFFFFFF8C (-116)
[ 59] = 0x25:  size 1  type GLOBAL    tag LOGICAL_MAXIMUM       value 0x00000001 (1)
[ 61] = 0x75:  size 1  type GLOBAL    tag REPORT_SIZE           value 0x00000001 (1)
[ 63] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000008 (8)
[ 65] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFFFF (-1)
[ 67] = 0x81:  size 1  type MAIN      tag INPUT                 value 0x00000002 (2)
[ 69] = 0xC0:  size 0  type MAIN      tag ENDCOLLECTION         value 0x00000000 (0)
[ 70] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000014 (20)
[ 72] = 0xA1:  size 1  type MAIN      tag COLLECTION            value 0x00000002 (2)
[ 74] = 0x85:  size 1  type GLOBAL    tag REPORT_ID             value 0x00000004 (4)
[ 76] = 0x15:  size 1  type GLOBAL    tag LOGICAL_MINIMUM       value 0x00000000 (0)
[ 78] = 0x25:  size 1  type GLOBAL    tag LOGICAL_MAXIMUM       value 0x00000001 (1)
[ 80] = 0x75:  size 1  type GLOBAL    tag REPORT_SIZE           value 0x00000001 (1)
[ 82] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x00000008 (8)
[ 84] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x0000005F (95)
[ 86] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000060 (96)
[ 88] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFF85 (-123)
[ 90] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0xFFFFFF86 (-122)
[ 92] = 0x91:  size 1  type MAIN      tag OUTPUT                value 0xFFFFFF86 (-122)
[ 94] = 0xC0:  size 0  type MAIN      tag ENDCOLLECTION         value 0x00000000 (0)
[ 95] = 0x06:  size 2  type GLOBAL    tag USAGE_PAGE            value 0xFFFFFFFF (-1)
[ 98] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000001 (1)
[100] = 0xA1:  size 1  type MAIN      tag COLLECTION            value 0x00000002 (2)
[102] = 0x85:  size 1  type GLOBAL    tag REPORT_ID             value 0xFFFFFFF0 (-16)
[104] = 0x15:  size 1  type GLOBAL    tag LOGICAL_MINIMUM       value 0x00000000 (0)
[106] = 0x26:  size 2  type GLOBAL    tag LOGICAL_MAXIMUM       value 0x000000FF (255)
[109] = 0x75:  size 1  type GLOBAL    tag REPORT_SIZE           value 0x00000008 (8)
[111] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x0000003F (63)
[113] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000002 (2)
[115] = 0x82:  size 2  type MAIN      tag INPUT                 value 0x00000202 (514)
[118] = 0x95:  size 1  type GLOBAL    tag REPORT_COUNT          value 0x0000003F (63)
[120] = 0x09:  size 1  type LOCAL     tag USAGE                 value 0x00000003 (3)
[122] = 0x92:  size 2  type MAIN      tag OUTPUT                value 0x00000202 (514)
[125] = 0xC0:  size 0  type MAIN      tag ENDCOLLECTION         value 0x00000000 (0)
[126] = 0xC0:  size 0  type MAIN      tag ENDCOLLECTION         value 0x00000000 (0)
</pre>

I want to use the parsed descriptor to decode the raw payload 
<pre>
020A5D41303530313038313933373800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D
</pre>

However, when dumping the report, the first field is 008c:0002 and not 0001:0003b:

<pre>
REPORT-------------------------
         type: input
           id: 0x02
         size: 504
   -FIELD-------------------------
           usage: 0x008C:0x0002
           flags: 0x00000002
       report id: 0x02
            type: input
          offset: 0
            size: 8
     logical min: 0
     logical max: 255
    physical min: 0
    physical max: 0
            unit: 0
        unit exp: 0
   -FIELD-------------------------
           usage: 0x008C:0x00FB
           flags: 0x00000002
       report id: 0x02
            type: input
          offset: 8
            size: 8
     logical min: 0
     logical max: 255
    physical min: 0
    physical max: 0
            unit: 0
        unit exp: 0
</pre>

At least the Linux USB subsystem decodes the first byte of the raw payload as 0001:003b, which I think is correct, right?

**Comment by nyholku** [comment]
You maybe well be right, this parser has never been in production use 
because I've not been able to figure out how to read out descriptors on 
all platforms. I will try to have a look at the parser tomorrow.

br Kusti

> Martin Blom <mailto:notifications@github.com>
> 21 February 2015 10:51
> Trying to parse the following descriptor using the HidParser:
>
> <pre>
> 058C0902A1010912A1028502150026FF00750895010501093B81029503058C09FB09FC09FD8102953809FE8202020666FF9502090009008102058C25017501950809FF8102C00914A10285041500250175019508095F0960098509869186C006FFFF0901A10285F0150026FF007508953F0902820202953F0903920202C0C0
> </pre>
>
> which yields:
> <pre>
> [ 0] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 2] = 0x09: size 1 type LOCAL tag USAGE value 0x00000002 (2)
> [ 4] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000001 (1)
> [ 6] = 0x09: size 1 type LOCAL tag USAGE value 0x00000012 (18)
> [ 8] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [ 10] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0x00000002 (2)
> [ 12] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [ 14] = 0x26: size 2 type GLOBAL tag LOGICAL_MAXIMUM value 0x000000FF 
> (255)
> [ 17] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000008 (8)
> [ 19] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000001 (1)
> [ 21] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0x00000001 (1)
> [ 23] = 0x09: size 1 type LOCAL tag USAGE value 0x0000003B (59)
> [ 25] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 27] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000003 (3)
> [ 29] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 31] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFB (-5)
> [ 33] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFC (-4)
> [ 35] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFD (-3)
> [ 37] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 39] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000038 (56)
> [ 41] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFE (-2)
> [ 43] = 0x82: size 2 type MAIN tag INPUT value 0x00000202 (514)
> [ 46] = 0x06: size 2 type GLOBAL tag USAGE_PAGE value 0xFFFFFF66 (-154)
> [ 49] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000002 (2)
> [ 51] = 0x09: size 1 type LOCAL tag USAGE value 0x00000000 (0)
> [ 53] = 0x09: size 1 type LOCAL tag USAGE value 0x00000000 (0)
> [ 55] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 57] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 59] = 0x25: size 1 type GLOBAL tag LOGICAL_MAXIMUM value 0x00000001 (1)
> [ 61] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000001 (1)
> [ 63] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000008 (8)
> [ 65] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFF (-1)
> [ 67] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 69] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [ 70] = 0x09: size 1 type LOCAL tag USAGE value 0x00000014 (20)
> [ 72] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [ 74] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0x00000004 (4)
> [ 76] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [ 78] = 0x25: size 1 type GLOBAL tag LOGICAL_MAXIMUM value 0x00000001 (1)
> [ 80] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000001 (1)
> [ 82] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000008 (8)
> [ 84] = 0x09: size 1 type LOCAL tag USAGE value 0x0000005F (95)
> [ 86] = 0x09: size 1 type LOCAL tag USAGE value 0x00000060 (96)
> [ 88] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFF85 (-123)
> [ 90] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFF86 (-122)
> [ 92] = 0x91: size 1 type MAIN tag OUTPUT value 0xFFFFFF86 (-122)
> [ 94] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [ 95] = 0x06: size 2 type GLOBAL tag USAGE_PAGE value 0xFFFFFFFF (-1)
> [ 98] = 0x09: size 1 type LOCAL tag USAGE value 0x00000001 (1)
> [100] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [102] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0xFFFFFFF0 (-16)
> [104] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [106] = 0x26: size 2 type GLOBAL tag LOGICAL_MAXIMUM value 0x000000FF 
> (255)
> [109] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000008 (8)
> [111] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x0000003F (63)
> [113] = 0x09: size 1 type LOCAL tag USAGE value 0x00000002 (2)
> [115] = 0x82: size 2 type MAIN tag INPUT value 0x00000202 (514)
> [118] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x0000003F (63)
> [120] = 0x09: size 1 type LOCAL tag USAGE value 0x00000003 (3)
> [122] = 0x92: size 2 type MAIN tag OUTPUT value 0x00000202 (514)
> [125] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [126] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> </pre>
>
> I want to use the parsed descriptor to decode the raw payload
> <pre>
> 020A5D41303530313038313933373800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D
> </pre>
>
> However, when dumping the report, the first field is 008c:0002 and not 
> 0001:0003b:
>
> <pre>
> REPORT-------------------------
> type: input
> id: 0x02
> size: 504
> -FIELD-------------------------
> usage: 0x008C:0x0002
> flags: 0x00000002
> report id: 0x02
> type: input
> offset: 0
> size: 8
> logical min: 0
> logical max: 255
> physical min: 0
> physical max: 0
> unit: 0
> unit exp: 0
> -FIELD-------------------------
> usage: 0x008C:0x00FB
> flags: 0x00000002
> report id: 0x02
> type: input
> offset: 8
> size: 8
> logical min: 0
> logical max: 255
> physical min: 0
> physical max: 0
> unit: 0
> unit exp: 0
> </pre>
>
> At least the Linux USB subsystem decodes the first byte of the raw 
> payload as 0001:003b, which I think is correct, right?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nyholku/purejavahidapi/issues/6

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by LeviticusMB** [comment]
I decided to roll my own. Hope you didn't spend too much time on this just because of me.

(My version [here](https://github.com/LeviticusMB/org.blom.martin.usb).)

**Comment by nyholku** [comment]
No, no time spent yet! I was busy correcting an other bug ;)

cheers Kusti


> Martin Blom <mailto:notifications@github.com>
> 21 February 2015 10:51
> Trying to parse the following descriptor using the HidParser:
>
> <pre>
> 058C0902A1010912A1028502150026FF00750895010501093B81029503058C09FB09FC09FD8102953809FE8202020666FF9502090009008102058C25017501950809FF8102C00914A10285041500250175019508095F0960098509869186C006FFFF0901A10285F0150026FF007508953F0902820202953F0903920202C0C0
> </pre>
>
> which yields:
> <pre>
> [ 0] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 2] = 0x09: size 1 type LOCAL tag USAGE value 0x00000002 (2)
> [ 4] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000001 (1)
> [ 6] = 0x09: size 1 type LOCAL tag USAGE value 0x00000012 (18)
> [ 8] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [ 10] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0x00000002 (2)
> [ 12] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [ 14] = 0x26: size 2 type GLOBAL tag LOGICAL_MAXIMUM value 0x000000FF 
> (255)
> [ 17] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000008 (8)
> [ 19] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000001 (1)
> [ 21] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0x00000001 (1)
> [ 23] = 0x09: size 1 type LOCAL tag USAGE value 0x0000003B (59)
> [ 25] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 27] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000003 (3)
> [ 29] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 31] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFB (-5)
> [ 33] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFC (-4)
> [ 35] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFD (-3)
> [ 37] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 39] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000038 (56)
> [ 41] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFE (-2)
> [ 43] = 0x82: size 2 type MAIN tag INPUT value 0x00000202 (514)
> [ 46] = 0x06: size 2 type GLOBAL tag USAGE_PAGE value 0xFFFFFF66 (-154)
> [ 49] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000002 (2)
> [ 51] = 0x09: size 1 type LOCAL tag USAGE value 0x00000000 (0)
> [ 53] = 0x09: size 1 type LOCAL tag USAGE value 0x00000000 (0)
> [ 55] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 57] = 0x05: size 1 type GLOBAL tag USAGE_PAGE value 0xFFFFFF8C (-116)
> [ 59] = 0x25: size 1 type GLOBAL tag LOGICAL_MAXIMUM value 0x00000001 (1)
> [ 61] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000001 (1)
> [ 63] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000008 (8)
> [ 65] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFFFF (-1)
> [ 67] = 0x81: size 1 type MAIN tag INPUT value 0x00000002 (2)
> [ 69] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [ 70] = 0x09: size 1 type LOCAL tag USAGE value 0x00000014 (20)
> [ 72] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [ 74] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0x00000004 (4)
> [ 76] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [ 78] = 0x25: size 1 type GLOBAL tag LOGICAL_MAXIMUM value 0x00000001 (1)
> [ 80] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000001 (1)
> [ 82] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x00000008 (8)
> [ 84] = 0x09: size 1 type LOCAL tag USAGE value 0x0000005F (95)
> [ 86] = 0x09: size 1 type LOCAL tag USAGE value 0x00000060 (96)
> [ 88] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFF85 (-123)
> [ 90] = 0x09: size 1 type LOCAL tag USAGE value 0xFFFFFF86 (-122)
> [ 92] = 0x91: size 1 type MAIN tag OUTPUT value 0xFFFFFF86 (-122)
> [ 94] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [ 95] = 0x06: size 2 type GLOBAL tag USAGE_PAGE value 0xFFFFFFFF (-1)
> [ 98] = 0x09: size 1 type LOCAL tag USAGE value 0x00000001 (1)
> [100] = 0xA1: size 1 type MAIN tag COLLECTION value 0x00000002 (2)
> [102] = 0x85: size 1 type GLOBAL tag REPORT_ID value 0xFFFFFFF0 (-16)
> [104] = 0x15: size 1 type GLOBAL tag LOGICAL_MINIMUM value 0x00000000 (0)
> [106] = 0x26: size 2 type GLOBAL tag LOGICAL_MAXIMUM value 0x000000FF 
> (255)
> [109] = 0x75: size 1 type GLOBAL tag REPORT_SIZE value 0x00000008 (8)
> [111] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x0000003F (63)
> [113] = 0x09: size 1 type LOCAL tag USAGE value 0x00000002 (2)
> [115] = 0x82: size 2 type MAIN tag INPUT value 0x00000202 (514)
> [118] = 0x95: size 1 type GLOBAL tag REPORT_COUNT value 0x0000003F (63)
> [120] = 0x09: size 1 type LOCAL tag USAGE value 0x00000003 (3)
> [122] = 0x92: size 2 type MAIN tag OUTPUT value 0x00000202 (514)
> [125] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> [126] = 0xC0: size 0 type MAIN tag ENDCOLLECTION value 0x00000000 (0)
> </pre>
>
> I want to use the parsed descriptor to decode the raw payload
> <pre>
> 020A5D41303530313038313933373800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000D
> </pre>
>
> However, when dumping the report, the first field is 008c:0002 and not 
> 0001:0003b:
>
> <pre>
> REPORT-------------------------
> type: input
> id: 0x02
> size: 504
> -FIELD-------------------------
> usage: 0x008C:0x0002
> flags: 0x00000002
> report id: 0x02
> type: input
> offset: 0
> size: 8
> logical min: 0
> logical max: 255
> physical min: 0
> physical max: 0
> unit: 0
> unit exp: 0
> -FIELD-------------------------
> usage: 0x008C:0x00FB
> flags: 0x00000002
> report id: 0x02
> type: input
> offset: 8
> size: 8
> logical min: 0
> logical max: 255
> physical min: 0
> physical max: 0
> unit: 0
> unit exp: 0
> </pre>
>
> At least the Linux USB subsystem decodes the first byte of the raw 
> payload as 0001:003b, which I think is correct, right?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nyholku/purejavahidapi/issues/6

-- 
Sent with Postbox <http://www.getpostbox.com>
