### ISSUE TITLE
errno 13 when opening device on fedora 30

### ISSUE THREAD

**Issue by dragonsKnight5** [nyholku/purejavahidapi#66]
Hi,
I'm encountering errno 13 when trying to open a connection to my device on Fedora 30,
my research into this has come across you mentioning this is a system error code from the
OS blocking access.

Which admin user groups do I need to add my user to to get around this?

Best Regards
dragonsKnight5

**Comment by nyholku** [comment]
Sorry, I'm not really a Linux user and I don't have the info at hand, there is probably an issue here in the git repo that has this info, search for. Also this is by no means purejavahidapi specific issue so plenty of answers in the web.
