### ISSUE TITLE
unable to connect to device

### ISSUE THREAD

**Issue by alfonz19** [nyholku/purejavahidapi#80]
just as in https://github.com/nyholku/purejavahidapi/issues/36

I'm getting

Exception in thread "main" java.lang.RuntimeException: Unable to open
	at alf.Main.test(Main.java:50)
	at alf.Main.main(Main.java:23)
Caused by: java.io.IOException: open() failed, errno 13
	at purejavahidapi.linux.HidDevice.<init>(HidDevice.java:68)
	at purejavahidapi.linux.LinuxBackend.openDevice(LinuxBackend.java:166)
	at purejavahidapi.PureJavaHidApi.openDevice(PureJavaHidApi.java:100)
	at alf.Main.test(Main.java:39)
	... 1 more

regardless of installed udev rules:

SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", TAG+="uaccess"

or

SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE="0666"

I'm trying to access streamdeck, and streamdeck-ui written in python (horribly) does not start without this udev rules, and after adding either one from above, it start working. So the udev rules are correct. I tested your code as a first thing after reboot, so not process (namely that python one) interferes.

if this is problem of udev rules, could you show what rules are required?

**Comment by nyholku** [comment]
This purely a Linux issue, nothing to do with PureJavaHidApi. 

I use rules like these for my devices:

SUBSYSTEMS=="usb", ATTRS{idProduct}=="eb93", ATTRS{idVendor}=="10ce", MODE="0666", GROUP="plugdev"
SUBSYSTEMS=="usb", ATTRS{idProduct}=="6020", ATTRS{idVendor}=="1d50", MODE="0666", GROUP="plugdev"

So yours look similar enough, though I'm no udev expert.

I something else grabbing your device before you can access it?

**Comment by alfonz19** [comment]
you are probably correct. With saddened heart I ran it as root and it works.
nothing grabs the device before, and with same configuration the streamdeck-ui rans just after purejavahidapi fails.

I have idProduct/idVendor correctly set, adding your `MODE="0666", GROUP="plugdev"` did not work for me... Do you happen to have any suggestion how to find out missing configuration? And it's surprising, that configuration is OK for python while insufficient for java...

**Comment by nyholku** [comment]
Sorry I'm out of suggestions. You might try to find the source for the Python/streamdeck open command and see what they do differently. I guess you have ensured no-one else opens the device because otherwise that might explain the issue. It has been a long time since I had to play with Linux but I think it is possible to open a device in shared or exclusive mode... not sure I remember this correctly. But something like that might explain why one software can open it and an other one cannot.

**Comment by alfonz19** [comment]
I was lucky in googling, finding this as a working solution:
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080",  MODE="0666", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl"

instead of using what was mentioned in my initial post.

So I can close this, you was correct, this is linux issue.
