### ISSUE TITLE
macosx: Enumeration repeats first device

### ISSUE THREAD

**Issue by IvoClarysse** [nyholku/purejavahidapi#9]
When enumerating USB devices using purejavahidapi on OS X 10.10.3, the device information for the first USB device gets repeated in subsequent entries.

For example, using the Example1 example:

    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fa601469210
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fa601468120
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fa6014699e0
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fa601468ad0

While this system does have 4 internal USB peripherals, only 1 of them is the keyboard/trackpad device.

Once an external USB peripheral device is plugged in, the enumeration yields:

    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fe469d22260
    VID = 0x046D PID = 0xC12B Manufacturer = Logitech Product = Harmony Remote Path = USB_046d_c12b_0x7fe469d21220
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fe469d22950
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fe469d207b0
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7fe469d21a50

**Comment by nyholku** [comment]
If you look carefully it is not actually repeated 100%, the path is different for each device. 

Look at the MacOXBackend.java and you see that the list comes more or less directly from the OS:

    		CFSetRef device_set = IOHIDManagerCopyDevices(MacOsXBackend.m_HidManager);

I do not know why and for what purpose the  keyboard/trackpad device is repeated, I have not investigated this as you cannot open them with PureJavaHidApi anyway. Looking at the device with Apple's USB Prober app I see that the keyboard/trackpad is a composite device with three interfaces, so maybe that is the explanation.

**Comment by IvoClarysse** [comment]
OK, by extracting the kUSBInterfaceNumber ( "bInterfaceNumber") property from the device instances, I can trace the returned entries to distinct HID-supporting USB interface. Interface 0x1 of the Apple Internal Keyboard / Trackpad is repeated twice though.

This does not happen when enumerating over a basic composite USB+Mouse USB HID device. (Here, just a single HID device is returned by IOHIDManagerCopyDevices for every USB interface)

    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7ff9a1707b40
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7ff9a17082f0
    VID = 0x1997 PID = 0x2433 Manufacturer =  Product = Mini Keyboard Path = USB_1997_2433_0x7ff9a1706260
    VID = 0x1997 PID = 0x2433 Manufacturer =  Product = Mini Keyboard Path = USB_1997_2433_0x7ff9a1706b30
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7ff9a17073f0
    VID = 0x05AC PID = 0x0259 Manufacturer = Apple Inc. Product = Apple Internal Keyboard / Trackpad Path = USB_05ac_0259_0x7ff9a1705a30

Looking at the output of 'ioreg' / 'IORegistryExplorer' illustrates that Apple's Multitouch USB device driver provides an additional IOHIDInterface instance underneath USB interface#1:


    $ ioreg | egrep '(IOUSBInterface|IOHIDInterface)' | cut -d, -f1
    | | | |   | +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |   | +-o Apple Internal Keyboard@0  <class IOUSBInterface
    | | | |   | |   +-o IOHIDInterface  <class IOHIDInterface
    | | | |   | +-o Touchpad@1  <class IOUSBInterface
    | | | |   | |   +-o IOHIDInterface  <class IOHIDInterface
    | | | |   | |   |       +-o IOHIDInterface  <class IOHIDInterface
    | | | |   | +-o Touchpad@2  <class IOUSBInterface
    | | | |   |     +-o IOHIDInterface  <class IOHIDInterface
    | | | |   | +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@1  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@2  <class IOUSBInterface
    | | | |   | +-o IOUSBInterface@3  <class IOUSBInterface
    | | | |     +-o IOUSBInterface@0  <class IOUSBInterface
    | | | |     |   +-o IOHIDInterface  <class IOHIDInterface
    | | | |     +-o IOUSBInterface@1  <class IOUSBInterface
    | | | |         +-o IOHIDInterface  <class IOHIDInterface
